def subjectMeBranchFifthSem():
    print("\nTheory : \n")
    print("Fundamental of Management \n")
    print("Heat Transfer\n")
    print("Dynamics of Machines\n")
    print("Production Management\n")
    print("Open Elective - I *\n")
    print("Open Elective - II *\n")
    print("Industry Visit and its report\n")
    print("\nLAB : \n")
    print("Heat Transfer\n")
    print("Dynamics of Machines\n")


def subjectMeBranchSixthSem():
    print("\nTheory : \n")
    print("Fundamental of Economics\n")
    print("Fluid Machines\n")
    print("Computer Aided Design (CAD LAB)\n")
    print("Design of Mechanical Drives\n")
    print("Professional Elective I\n")
    print("Open Elective - III **\n")
    print("Open Elective - IV **\n")
    print("\nLAB : \n")
    print("Fluid Machines\n")
    print("Professional Elective I\n")
