def subjectCivilBranchThirdSem():
    print("\nTheory : \n")
    print("Engineering Mathematics III \n")
    print("Strength of Materials\n")
    print("Geotechnical Engineering\n")
    print("Fluid Mechanics\n")
    print("Water Supply Engineering \n")
    print("\nLAB : \n")
    print("Strength of Materials\n")
    print("Geotechnical Engineering\n")
    print("Water Supply Engineering \n")

def subjectCivilBranchFourthSem():
    print("\nTheory : \n")
    print("Advance Mathematical Techniques \n")
    print("Concrete Technology\n")
    print("Surveying \n")
    print("Structural Analysis\n")
    print("Transportation Engineering \n")
    print("\nLAB : \n")
    print("Concrete Technology\n")
    print("Surveying \n")
    print("Structural Analysis\n")
    print("Transportation Engineering \n")