def subjectCivilBranchFifthSem():
    print("\nTheory : \n")
    print("Fundamental of Management \n")
    print("Reinforced Concrete Structures\n")
    print("Advanced Structural Analysis\n")
    print("Professional Elective-I\n")
    print("Open Elective - I *\n")
    print("Open Elective - II *\n")
    print("\nLAB : \n")
    print("Analysis and Design Studio\n")
    print("Professional Elective -I\n")

def subjectCivilBranchSixthSem():
    print("\nTheory : \n")
    print("Fundamental of Economics \n")
    print("Steel Structures\n")
    print("Hydraulic Engineering\n")
    print("Foundation Engineering\n")
    print("Professional Elective -II\n")
    print("Open Elective - III ** \n")
    print("Open Elective - IV ** \n")
    print("Industry Visit and its report \n")
    print("\nLAB : \n")
    print("Building Design Drawing\n")
    print(" Hydraulic Engineering\n")
