def subjectItBranchFirstSem():
    print("\nTheory : \n")
    print("Engineering Mathematics I \n")
    print("Engineering Physics\n")
    print("Communications Skills\n")
    print("Engineering Mechanics\n")
    print("Introduction to Computer Programing\n")
    print("Workshop Practice\n")
    print("\nLAB : \n")
    print("Engineering Physics\n")
    print("Engineering Mechanics\n")
    print("Introduction to Computer Programing\n")


def subjectItBranchSecondSem():
    print("\nTheory : \n")
    print("Engineering Mathematics II \n")
    print("Engineering Chemistry\n")
    print("Social Sciences\n")
    print("Electrical Engineering\n")
    print("Engineering Graphics\n")
    print("Basic Electronics\n")
    print("\nLAB : \n")
    print(" Engineering Chemistry\n")
    print("Electrical Engineering\n")
    print("Engineering Graphics\n")
